docs: # 文档类变更规则
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - "**/*.md" # 任意 md 文件
          - all-globs-to-all-files:
              - "!frontend/**" # 排除前端目录
              - "!backend/**" # 排除后端目录
              - "!.github/**"
              - "!scripts/**"
              - "!.gitignore"
              - "!.pre-commit-config.yaml"

internal: # 内部/配置类变更规则
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - .github/** # .github 目录下的配置
              - scripts/** # 脚本目录
              - .gitignore
              - .pre-commit-config.yaml
          - all-globs-to-all-files:
              - "!./**/*.md" # 排除 md 文档
              - "!frontend/**"
              - "!backend/**"
