// This file is auto-generated by @hey-api/openapi-ts

export type ApiResponse_bool_ = {
    code?: number;
    message?: string;
    data?: (unknown | null);
};

export type ApiResponse_ItemPublic_ = {
    code?: number;
    message?: string;
    data?: (unknown | null);
};

export type ApiResponse_NoneType_ = {
    code?: number;
    message?: string;
    data?: (unknown | null);
};

export type ApiResponse_PagedData_ItemPublic__ = {
    code?: number;
    message?: string;
    data?: (unknown | null);
};

export type ApiResponse_PagedData_UserPublic__ = {
    code?: number;
    message?: string;
    data?: (unknown | null);
};

export type ApiResponse_Token_ = {
    code?: number;
    message?: string;
    data?: (unknown | null);
};

export type ApiResponse_UserPublic_ = {
    code?: number;
    message?: string;
    data?: (unknown | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

// ==================== 手动添加的业务类型 ====================
// OpenAPI 生成器没有正确导出 ApiResponse 内部的泛型类型

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type PagedData<T> = {
    items: Array<T>;
    total: number;
    page: number;
    page_size: number;
    pages: number;
};

export type Message = {
    message: string;
};


export type ItemsReadItemsData = {
    page?: number;
    pageSize?: number;
};

export type ItemsReadItemsResponse = (ApiResponse_PagedData_ItemPublic__);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ApiResponse_ItemPublic_);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ApiResponse_ItemPublic_);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ApiResponse_ItemPublic_);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (ApiResponse_NoneType_);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (ApiResponse_Token_);

export type LoginTestTokenResponse = (ApiResponse_UserPublic_);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (ApiResponse_NoneType_);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (ApiResponse_NoneType_);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (ApiResponse_UserPublic_);

export type UsersReadUsersData = {
    page?: number;
    pageSize?: number;
};

export type UsersReadUsersResponse = (ApiResponse_PagedData_UserPublic__);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (ApiResponse_UserPublic_);

export type UsersReadUserMeResponse = (ApiResponse_UserPublic_);

export type UsersDeleteUserMeResponse = (ApiResponse_NoneType_);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (ApiResponse_UserPublic_);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (ApiResponse_NoneType_);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (ApiResponse_UserPublic_);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (ApiResponse_UserPublic_);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (ApiResponse_UserPublic_);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (ApiResponse_NoneType_);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (ApiResponse_NoneType_);

export type UtilsHealthCheckResponse = (ApiResponse_bool_);